# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  BuildConfiguration: Release

jobs:
- job: Docker
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: Docker@1
    displayName: Build docker image
    inputs:
      command: build
      dockerFile: Dockerfile
      imageName: cwoolum/ThinNugetProxy:$(Build.SourceVersion)

  - task: Docker@1
    displayName: Tag latest docker image
    condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
    inputs:
      command: tag
      imageName: cwoolum/ThinNugetProxy:$(Build.SourceVersion)
      arguments: cwoolum/ThinNugetProxy:latest

  - task: Docker@1
    displayName: Push docker image
    condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
    inputs:
      command: push
      containerRegistryType: 'Container Registry'
      dockerRegistryEndpoint: 'Docker Hub'
      imageName: cwoolum/ThinNugetProxy
