# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  BuildConfiguration: Release

jobs:
- job: Docker
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'cwoolum/ThinNugetProxy'
      command: 'buildAndPush'
      Dockerfile: 'src/NugetProxy/Dockerfile'
      buildContext: ''
      tags: |
        $(Build.SourceVersion)
        latest
  
  - task: Docker@2
    displayName: Push docker image
    condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
    inputs:
      containerRegistry: 'Docker'
      repository: 'cwoolum/ThinNugetProxy'
      command: 'push'
